#!/bin/sh
# Export htdocs/ from the current HEAD to the gh-pages branch.

SOURCE=htdocs
TARGET=gh-pages

HTDOCS_TREE=`git write-tree --prefix=${SOURCE}`
HTDOCS_COMMIT=`echo 'Placeholder commit for gh-pages' | git commit-tree ${HTDOCS_TREE}`

git cat-file commit "$HTDOCS_COMMIT"
git branch -f ${TARGET} ${HTDOCS_COMMIT}
